#!/usr/bin/env pwsh
<#
.SYNOPSIS
    CDK outputs.json から frontend/.env.local を自動生成

.DESCRIPTION
    CDKデプロイ後に生成される outputs.json から AppSync エンドポイントや
    Cognito 設定を読み取り、フロントエンドの .env.local ファイルを自動生成します。

.EXAMPLE
    pwsh scripts/update-frontend-env.ps1
#>

$ErrorActionPreference = "Stop"

# Paths
$outputsPath = "cdk/outputs.json"
$envPath = "frontend/.env.local"

Write-Host "🔍 Checking for CDK outputs..." -ForegroundColor Cyan

if (!(Test-Path $outputsPath)) {
    Write-Error "❌ outputs.json not found at '$outputsPath'. Run 'cdk deploy --all --outputs-file outputs.json' first."
    exit 1
}

Write-Host "✅ Found outputs.json" -ForegroundColor Green

# Parse outputs.json
$outputs = Get-Content $outputsPath -Raw | ConvertFrom-Json

# Find AppSync stack (contains "appsync" in stack name)
$appsyncStackName = $outputs.PSObject.Properties.Name | Where-Object { $_ -like "*appsync*" } | Select-Object -First 1
$cognitoStackName = $outputs.PSObject.Properties.Name | Where-Object { $_ -like "*cognito*" } | Select-Object -First 1

if (!$appsyncStackName) {
    Write-Error "❌ AppSync stack not found in outputs.json. Expected stack name containing 'appsync'."
    exit 1
}

if (!$cognitoStackName) {
    Write-Error "❌ Cognito stack not found in outputs.json. Expected stack name containing 'cognito'."
    exit 1
}

Write-Host "📦 Found AppSync stack: $appsyncStackName" -ForegroundColor Green
Write-Host "🔐 Found Cognito stack: $cognitoStackName" -ForegroundColor Green

# Extract values
$appsyncStack = $outputs.$appsyncStackName
$cognitoStack = $outputs.$cognitoStackName

$appsyncEndpoint = $appsyncStack.GraphqlApiUrl
$userPoolId = $cognitoStack.UserPoolId
$userPoolClientId = $cognitoStack.UserPoolClientId

if (!$appsyncEndpoint -or !$userPoolId -or !$userPoolClientId) {
    Write-Error "❌ Missing required outputs. Expected: GraphqlApiUrl (AppSync), UserPoolId & UserPoolClientId (Cognito)"
    Write-Error "   AppSync Endpoint: $appsyncEndpoint"
    Write-Error "   User Pool ID: $userPoolId"
    Write-Error "   User Pool Client: $userPoolClientId"
    exit 1
}

# Generate .env.local content
$envContent = @"
# Auto-generated by scripts/update-frontend-env.ps1
# DO NOT EDIT MANUALLY - This file is regenerated from CDK outputs

NEXT_PUBLIC_APPSYNC_ENDPOINT=$appsyncEndpoint
NEXT_PUBLIC_USER_POOL_ID=$userPoolId
NEXT_PUBLIC_USER_POOL_CLIENT_ID=$userPoolClientId
NEXT_PUBLIC_AWS_REGION=ap-northeast-1
"@

# Write to file
Set-Content -Path $envPath -Value $envContent -Encoding UTF8

Write-Host "✅ Successfully updated $envPath" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Generated configuration:" -ForegroundColor Cyan
Write-Host "  AppSync Endpoint: $appsyncEndpoint" -ForegroundColor White
Write-Host "  User Pool ID:     $userPoolId" -ForegroundColor White
Write-Host "  User Pool Client: $userPoolClientId" -ForegroundColor White
Write-Host ""
Write-Host "🚀 You can now run 'npm run dev' in the frontend directory" -ForegroundColor Green
